"""
Luxera Project Module

Project file handling for saving and loading Luxera projects.
"""

from luxera.project.project_file import (
    LuminaireReference,
    RoomData,
    CalculationSettings,
    ProjectMetadata,
    LuxeraProject,
    save_project,
    load_project,
    create_new_project,
    create_office_project,
    create_warehouse_project,
)
from luxera.project.schema import (
    Project,
    Geometry,
    RoomSpec,
    ZoneSpec,
    SurfaceSpec,
    OpeningSpec,
    ObstructionSpec,
    LevelSpec,
    CoordinateSystemSpec,
    MaterialSpec,
    MaterialLibraryEntry,
    PhotometryAsset,
    LuminaireFamily,
    LuminaireInstance,
    CalcGrid,
    WorkplaneSpec,
    VerticalPlaneSpec,
    PointSetSpec,
    GlareViewSpec,
    EscapeRouteSpec,
    RoadwaySpec,
    RoadwayGridSpec,
    ComplianceProfile,
    ProjectVariant,
    DaylightAnnualSpec,
    DaylightSpec,
    EmergencyModeSpec,
    EmergencySpec,
    JobSpec,
    JobResultRef,
)
from luxera.project.io import save_project_schema, load_project_schema
from luxera.project.variants import VariantCompareResult, run_job_for_variants
from luxera.project.presets import en12464_direct_job, en13032_radiosity_job, default_compliance_profiles

__all__ = [
    "LuminaireReference",
    "RoomData",
    "CalculationSettings",
    "ProjectMetadata",
    "LuxeraProject",
    "save_project",
    "load_project",
    "create_new_project",
    "create_office_project",
    "create_warehouse_project",
    "Project",
    "Geometry",
    "RoomSpec",
    "ZoneSpec",
    "SurfaceSpec",
    "OpeningSpec",
    "ObstructionSpec",
    "LevelSpec",
    "CoordinateSystemSpec",
    "MaterialSpec",
    "MaterialLibraryEntry",
    "PhotometryAsset",
    "LuminaireFamily",
    "LuminaireInstance",
    "CalcGrid",
    "WorkplaneSpec",
    "VerticalPlaneSpec",
    "PointSetSpec",
    "GlareViewSpec",
    "EscapeRouteSpec",
    "RoadwaySpec",
    "RoadwayGridSpec",
    "ComplianceProfile",
    "ProjectVariant",
    "DaylightAnnualSpec",
    "DaylightSpec",
    "EmergencyModeSpec",
    "EmergencySpec",
    "JobSpec",
    "JobResultRef",
    "save_project_schema",
    "load_project_schema",
    "VariantCompareResult",
    "run_job_for_variants",
    "en12464_direct_job",
    "en13032_radiosity_job",
    "default_compliance_profiles",
]
