from __future__ import annotations

import argparse
from collections.abc import Callable, Mapping


HandlerMap = Mapping[str, Callable[[argparse.Namespace], int]]


def register_project_commands(sub: argparse._SubParsersAction[argparse.ArgumentParser], handlers: HandlerMap) -> None:
    demo = sub.add_parser("demo", help="Write a small demo .ies file to disk.")
    demo.add_argument("--out", default="data/ies_samples/demo.ies", help="Output .ies path")
    demo.set_defaults(func=handlers["demo"])

    view = sub.add_parser("view", help="Parse an IES file and save default plots (PNG), optionally PDF.")
    view.add_argument("file", help="Path to .ies file")
    view.add_argument("--out", default="out", help="Output directory (default: out)")
    view.add_argument("--stem", default="luxera_view", help="Filename stem for outputs")
    view.add_argument("--pdf", action="store_true", help="Also generate a PDF report")
    view.add_argument("--horizontal-plane", type=float, default=None, help="Optional C-plane angle (degrees) for plot selection")
    view.set_defaults(func=handlers["view"])

    gui = sub.add_parser("gui", help="Launch Luxera View interactive GUI.")
    gui.set_defaults(func=handlers["gui"])

    init = sub.add_parser("init", help="Initialize a new Luxera project file (schema v5).")
    init.add_argument("project", help="Path to project JSON")
    init.add_argument("--name", default=None, help="Project name (default: filename stem)")
    init.set_defaults(func=handlers["init"])

    add_photometry = sub.add_parser("add-photometry", help="Add an IES/LDT asset to a project.")
    add_photometry.add_argument("project", help="Path to project JSON")
    add_photometry.add_argument("file", help="Path to IES/LDT file")
    add_photometry.add_argument("--id", default=None, help="Optional asset id")
    add_photometry.add_argument("--format", default=None, help="Override format (IES or LDT)")
    add_photometry.set_defaults(func=handlers["add_photometry"])

    add_luminaire = sub.add_parser("add-luminaire", help="Add a luminaire instance to a project.")
    add_luminaire.add_argument("project", help="Path to project JSON")
    add_luminaire.add_argument("--asset", required=True, help="Photometry asset id")
    add_luminaire.add_argument("--id", default=None, help="Optional luminaire id")
    add_luminaire.add_argument("--name", default=None, help="Luminaire name")
    add_luminaire.add_argument("--x", type=float, required=True)
    add_luminaire.add_argument("--y", type=float, required=True)
    add_luminaire.add_argument("--z", type=float, required=True)
    add_luminaire.add_argument("--yaw", type=float, default=0.0)
    add_luminaire.add_argument("--pitch", type=float, default=0.0)
    add_luminaire.add_argument("--roll", type=float, default=0.0)
    add_luminaire.add_argument("--maintenance", type=float, default=1.0)
    add_luminaire.add_argument("--multiplier", type=float, default=1.0)
    add_luminaire.add_argument("--tilt", type=float, default=0.0, help="Luminaire tilt angle (degrees)")
    add_luminaire.set_defaults(func=handlers["add_luminaire"])

    add_grid = sub.add_parser("add-grid", help="Add a calculation grid to a project.")
    add_grid.add_argument("project", help="Path to project JSON")
    add_grid.add_argument("--id", default=None, help="Optional grid id")
    add_grid.add_argument("--name", default=None, help="Grid name")
    add_grid.add_argument("--origin-x", type=float, default=0.0)
    add_grid.add_argument("--origin-y", type=float, default=0.0)
    add_grid.add_argument("--origin-z", type=float, default=0.0)
    add_grid.add_argument("--width", type=float, required=True)
    add_grid.add_argument("--height", type=float, required=True)
    add_grid.add_argument("--elevation", type=float, required=True)
    add_grid.add_argument("--nx", type=int, required=True)
    add_grid.add_argument("--ny", type=int, required=True)
    add_grid.add_argument("--room-id", default=None)
    add_grid.add_argument("--zone-id", default=None)
    add_grid.set_defaults(func=handlers["add_grid"])

    add_room = sub.add_parser("add-room", help="Add a simple rectangular room to a project.")
    add_room.add_argument("project", help="Path to project JSON")
    add_room.add_argument("--id", default=None, help="Optional room id")
    add_room.add_argument("--name", default=None, help="Room name")
    add_room.add_argument("--width", type=float, required=True)
    add_room.add_argument("--length", type=float, required=True)
    add_room.add_argument("--height", type=float, required=True)
    add_room.add_argument("--origin-x", type=float, default=0.0)
    add_room.add_argument("--origin-y", type=float, default=0.0)
    add_room.add_argument("--origin-z", type=float, default=0.0)
    add_room.add_argument("--floor-reflectance", type=float, default=0.2)
    add_room.add_argument("--wall-reflectance", type=float, default=0.5)
    add_room.add_argument("--ceiling-reflectance", type=float, default=0.7)
    add_room.add_argument("--activity-type", default=None, help="EN 12464 activity type enum name")
    add_room.set_defaults(func=handlers["add_room"])

    add_roadway_grid = sub.add_parser("add-roadway-grid", help="Add a roadway calculation grid to a project.")
    add_roadway_grid.add_argument("project", help="Path to project JSON")
    add_roadway_grid.add_argument("--id", default=None, help="Optional roadway grid id")
    add_roadway_grid.add_argument("--name", default=None, help="Grid name")
    add_roadway_grid.add_argument("--lane-width", type=float, required=True)
    add_roadway_grid.add_argument("--road-length", type=float, required=True)
    add_roadway_grid.add_argument("--nx", type=int, required=True)
    add_roadway_grid.add_argument("--ny", type=int, required=True)
    add_roadway_grid.add_argument("--origin-x", type=float, default=0.0)
    add_roadway_grid.add_argument("--origin-y", type=float, default=0.0)
    add_roadway_grid.add_argument("--origin-z", type=float, default=0.0)
    add_roadway_grid.add_argument("--roadway-id", default=None, help="Optional roadway object id")
    add_roadway_grid.add_argument("--num-lanes", type=int, default=1)
    add_roadway_grid.add_argument("--longitudinal-points", type=int, default=None)
    add_roadway_grid.add_argument("--transverse-points-per-lane", type=int, default=None)
    add_roadway_grid.add_argument("--pole-spacing-m", type=float, default=None)
    add_roadway_grid.add_argument("--mounting-height-m", type=float, default=None)
    add_roadway_grid.add_argument("--setback-m", type=float, default=None)
    add_roadway_grid.add_argument("--observer-height-m", type=float, default=1.5)
    add_roadway_grid.add_argument("--observer-method", type=str, default="default")
    add_roadway_grid.add_argument("--observers-json", type=str, default=None, help="JSON array of roadway observer definitions")
    add_roadway_grid.set_defaults(func=handlers["add_roadway_grid"])

    add_roadway = sub.add_parser("add-roadway", help="Add a roadway layout object.")
    add_roadway.add_argument("project", help="Path to project JSON")
    add_roadway.add_argument("--id", default=None, help="Optional roadway id")
    add_roadway.add_argument("--name", default=None, help="Roadway name")
    add_roadway.add_argument("--start-x", type=float, required=True)
    add_roadway.add_argument("--start-y", type=float, required=True)
    add_roadway.add_argument("--start-z", type=float, default=0.0)
    add_roadway.add_argument("--end-x", type=float, required=True)
    add_roadway.add_argument("--end-y", type=float, required=True)
    add_roadway.add_argument("--end-z", type=float, default=0.0)
    add_roadway.add_argument("--num-lanes", type=int, default=1)
    add_roadway.add_argument("--lane-width", type=float, default=3.5)
    add_roadway.add_argument("--mounting-height-m", type=float, default=None)
    add_roadway.add_argument("--setback-m", type=float, default=None)
    add_roadway.add_argument("--pole-spacing-m", type=float, default=None)
    add_roadway.add_argument("--tilt-deg", type=float, default=None)
    add_roadway.add_argument("--aim-deg", type=float, default=None)
    add_roadway.add_argument("--segment-json", type=str, default=None, help="JSON object for roadway segment overrides")
    add_roadway.add_argument("--pole-rows-json", type=str, default=None, help="JSON array for roadway pole row definitions")
    add_roadway.add_argument("--observers-json", type=str, default=None, help="JSON array of roadway observer definitions")
    add_roadway.set_defaults(func=handlers["add_roadway"])

    add_escape_route = sub.add_parser("add-escape-route", help="Add an emergency escape route polyline.")
    add_escape_route.add_argument("project", help="Path to project JSON")
    add_escape_route.add_argument("--id", default=None, help="Optional route id")
    add_escape_route.add_argument("--name", default=None, help="Optional route name")
    add_escape_route.add_argument("--polyline", required=True, help='Semicolon separated points "x,y[,z];x,y[,z]"')
    add_escape_route.add_argument("--width-m", type=float, default=1.0)
    add_escape_route.add_argument("--height-m", type=float, default=0.0)
    add_escape_route.add_argument("--spacing-m", type=float, default=0.5)
    add_escape_route.add_argument("--end-margin-m", type=float, default=0.0)
    add_escape_route.set_defaults(func=handlers["add_escape_route"])

    add_compliance_profile = sub.add_parser("add-compliance-profile", help="Add a compliance profile (indoor/roadway/emergency/custom).")
    add_compliance_profile.add_argument("project", help="Path to project JSON")
    add_compliance_profile.add_argument("--id", default=None)
    add_compliance_profile.add_argument("--name", required=True)
    add_compliance_profile.add_argument("--domain", choices=["indoor", "roadway", "emergency", "custom"], required=True)
    add_compliance_profile.add_argument("--standard-ref", required=True)
    add_compliance_profile.add_argument("--thresholds", required=True, help='JSON map, e.g. {"avg_min_lux":1.0}')
    add_compliance_profile.add_argument("--notes", default=None)
    add_compliance_profile.set_defaults(func=handlers["add_compliance_profile"])

    add_profile_presets = sub.add_parser("add-profile-presets", help="Add default compliance profile presets.")
    add_profile_presets.add_argument("project", help="Path to project JSON")
    add_profile_presets.set_defaults(func=handlers["add_profile_presets"])

    add_job = sub.add_parser("add-job", help="Add a calculation job to a project.")
    add_job.add_argument("project", help="Path to project JSON")
    add_job.add_argument("--id", default=None, help="Optional job id")
    add_job.add_argument("--type", choices=["direct", "radiosity", "roadway", "emergency", "daylight"], default="direct")
    add_job.add_argument("--backend", choices=["cpu", "df", "radiance"], default="cpu")
    add_job.add_argument("--seed", type=int, default=0)
    add_job.add_argument("--preset", choices=["en12464_direct", "en13032_radiosity"], default=None)
    add_job.add_argument("--max-iterations", type=int, default=100)
    add_job.add_argument("--convergence-threshold", type=float, default=0.001)
    add_job.add_argument("--patch-max-area", type=float, default=0.5)
    add_job.add_argument("--method", choices=["GATHERING", "SHOOTING", "MATRIX"], default="GATHERING")
    add_job.add_argument("--use-visibility", action="store_true", default=True)
    add_job.add_argument("--no-visibility", action="store_true", default=False, help="Disable visibility in form factors")
    add_job.add_argument("--ambient-light", type=float, default=0.0)
    add_job.add_argument("--monte-carlo-samples", type=int, default=16)
    add_job.add_argument("--ugr-grid-spacing", type=float, default=2.0)
    add_job.add_argument("--ugr-eye-heights", type=str, default="1.2,1.7", help="Comma-separated eye heights in meters")
    add_job.add_argument("--use-occlusion", action="store_true", default=False, help="Enable geometry occlusion for direct jobs")
    add_job.add_argument("--no-occlusion", action="store_true", default=False, help="Disable geometry occlusion for direct jobs")
    add_job.add_argument("--occlusion-include-room-shell", action="store_true", default=False, help="Use room shell surfaces as occluders")
    add_job.add_argument("--occlusion-epsilon", type=float, default=1e-6, help="Ray epsilon for occlusion tests")
    add_job.add_argument("--road-class", default="M3", help="Roadway class label (e.g., M3, P2)")
    add_job.add_argument("--road-surface-class", default="R3", help="Road surface class preset id (R1-R4)")
    add_job.add_argument("--glare-method", default="rp8_veiling_ratio", choices=["rp8_veiling_ratio", "ti_proxy_percent"], help="Roadway disability glare output metric method")
    add_job.add_argument("--road-surface-reflectance", type=float, default=0.07)
    add_job.add_argument("--observer-height-m", type=float, default=1.5)
    add_job.add_argument("--observer-back-offset-m", type=float, default=60.0)
    add_job.add_argument("--observer-lateral-positions", default=None, help="Comma-separated lateral positions in meters")
    add_job.add_argument("--compliance-profile-id", default=None, help="Optional compliance profile id")
    add_job.add_argument("--emergency-mode", choices=["escape_route", "open_area"], default="escape_route")
    add_job.add_argument("--target-min-lux", type=float, default=1.0)
    add_job.add_argument("--target-uniformity", type=float, default=0.1)
    add_job.add_argument("--battery-duration-min", type=float, default=60.0)
    add_job.add_argument("--battery-end-factor", type=float, default=0.5)
    add_job.add_argument("--battery-curve", choices=["linear", "exponential"], default="linear")
    add_job.add_argument("--battery-steps", type=int, default=7)
    add_job.add_argument("--emergency-standard", choices=["EN1838", "BS5266"], default="EN1838")
    add_job.add_argument("--emergency-factor", type=float, default=1.0)
    add_job.add_argument("--route-min-lux", type=float, default=1.0)
    add_job.add_argument("--route-u0-min", type=float, default=0.1)
    add_job.add_argument("--open-area-min-lux", type=float, default=0.5)
    add_job.add_argument("--open-area-u0-min", type=float, default=0.1)
    add_job.add_argument("--include-luminaires", default=None, help="Comma-separated luminaire ids")
    add_job.add_argument("--exclude-luminaires", default=None, help="Comma-separated luminaire ids")
    add_job.add_argument("--routes", default=None, help="Comma-separated escape route ids")
    add_job.add_argument("--open-area-targets", default=None, help="Comma-separated grid ids")
    add_job.add_argument("--daylight-mode", choices=["daylight_factor", "annual_proxy", "df", "radiance", "annual"], default="daylight_factor")
    add_job.add_argument("--exterior-horizontal-illuminance-lux", type=float, default=10000.0)
    add_job.add_argument("--daylight-factor-percent", type=float, default=2.0)
    add_job.add_argument("--daylight-target-lux", type=float, default=300.0)
    add_job.add_argument("--annual-hours", type=int, default=8760)
    add_job.add_argument("--daylight-weather-file", default=None, help="EPW weather file path for annual daylight mode")
    add_job.add_argument("--daylight-occupancy-schedule", default="office_8_to_18", help="Occupancy schedule preset or CSV-like weights")
    add_job.add_argument("--weather-hourly-lux-file", default=None, help="Optional file with comma/newline-separated hourly exterior lux values")
    add_job.add_argument("--daylight-depth-attenuation", type=float, default=2.0)
    add_job.add_argument("--sda-threshold-ratio", type=float, default=0.5)
    add_job.add_argument("--udi-low-lux", type=float, default=100.0)
    add_job.add_argument("--udi-high-lux", type=float, default=2000.0)
    add_job.set_defaults(func=handlers["add_job"])

    run = sub.add_parser("run", help="Run a project job and store results.")
    run.add_argument("project", help="Path to project JSON")
    run.add_argument("job_id", help="Job id to run")
    run.set_defaults(func=handlers["run_job"])

    daylight = sub.add_parser("daylight", help="Run a daylight job by id.")
    daylight.add_argument("project", help="Path to project JSON")
    daylight.add_argument("--job", dest="job_id", required=True, help="Daylight job id")
    daylight.set_defaults(func=handlers["daylight"])

    run_all = sub.add_parser("run-all", help="Validate, run, and optionally generate report and audit bundle.")
    run_all.add_argument("project", help="Path to project JSON")
    run_all.add_argument("--job", dest="job_id", required=True, help="Job id to run")
    run_all.add_argument("--report", action="store_true", help="Generate report.pdf in the result directory")
    run_all.add_argument("--bundle", action="store_true", help="Generate audit_bundle.zip in the result directory")
    run_all.set_defaults(func=handlers["run_all"])

    export_debug = sub.add_parser("export-debug", help="Export a debug bundle zip for a job result.")
    export_debug.add_argument("project", help="Path to project JSON")
    export_debug.add_argument("job_id", help="Job id to export")
    export_debug.add_argument("--out", required=True, help="Output .zip path")
    export_debug.set_defaults(func=handlers["export_debug"])

    export_client = sub.add_parser("export-client", help="Export a client bundle zip for a job result.")
    export_client.add_argument("project", help="Path to project JSON")
    export_client.add_argument("job_id", help="Job id to export")
    export_client.add_argument("--out", required=True, help="Output .zip path")
    export_client.set_defaults(func=handlers["export_client"])

    export_backend_compare = sub.add_parser("export-backend-compare", help="Export backend comparison HTML for a job result.")
    export_backend_compare.add_argument("project", help="Path to project JSON")
    export_backend_compare.add_argument("job_id", help="Job id to export")
    export_backend_compare.add_argument("--out", required=True, help="Output .html path")
    export_backend_compare.set_defaults(func=handlers["export_backend_compare"])

    export_roadway_report = sub.add_parser("export-roadway-report", help="Export roadway report HTML for a roadway job result.")
    export_roadway_report.add_argument("project", help="Path to project JSON")
    export_roadway_report.add_argument("job_id", help="Job id to export")
    export_roadway_report.add_argument("--out", required=True, help="Output .html path")
    export_roadway_report.set_defaults(func=handlers["export_roadway_report"])

    compare_results = sub.add_parser("compare-results", help="Compare two job results and output deltas.")
    compare_results.add_argument("project", help="Path to project JSON")
    compare_results.add_argument("job_a", help="Reference job id")
    compare_results.add_argument("job_b", help="Comparison job id")
    compare_results.add_argument("--out", default=None, help="Optional output JSON path")
    compare_results.set_defaults(func=handlers["compare_results"])

    compare_variants = sub.add_parser("compare-variants", help="Run a job for selected variants and export comparison table.")
    compare_variants.add_argument("project", help="Path to project JSON")
    compare_variants.add_argument("job_id", help="Job id to run for all selected variants")
    compare_variants.add_argument("--variants", required=True, help="Comma-separated variant ids")
    compare_variants.add_argument("--baseline", default=None, help="Optional baseline variant id for delta columns")
    compare_variants.set_defaults(func=handlers["compare_variants"])
